name: AI Daily Recap

on:
  schedule:
    - cron: "0 6 * * *"  # runs daily at midnight CST (6 AM UTC)
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate AI summary
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          commits=$(git log --since="24 hours ago" --pretty=format:"%h - %s (%an)" | head -n 50)
          echo "Commits collected:"
          echo "$commits"

          summary=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are an AI assistant summarizing GitHub commits.\"},
                {\"role\": \"user\", \"content\": \"Summarize the following commit list in a clear daily project update:\n$commits\"}
              ]
            }" | jq -r '.choices[0].message.content')

          payload="{\"content\": \"**AI Summary for $(date +'%Y-%m-%d')**\n$summary\"}"
          curl -s -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK_URL"
