name: Commit to Discord (AI, @everyone)

on:
  push:
    branches: [ main ]

jobs:
  explain-and-post:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather commit info + diff
        id: info
        shell: bash
        run: |
          set -e
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "REPO=${GITHUB_REPOSITORY}" >> $GITHUB_OUTPUT
          echo "ACTOR=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT

          {
            echo "TITLE<<'__EOF__'"
            git log -1 --pretty=%s
            echo "__EOF__"
            echo "BODY<<'__EOF__'"
            git log -1 --pretty=%b
            echo "__EOF__"
          } >> "$GITHUB_OUTPUT"

          BEFORE="${{ github.event.before }}"
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            BEFORE=$(git rev-parse HEAD~1 || echo "")
          fi

          if [ -n "$BEFORE" ]; then
            git diff --name-only "$BEFORE" "$GITHUB_SHA" > changed_files.txt
            git diff --no-color --unified=0 "$BEFORE" "$GITHUB_SHA" > diff.txt
          else
            git show --name-only --pretty="" "$GITHUB_SHA" > changed_files.txt
            git show --no-color --unified=0 "$GITHUB_SHA" > diff.txt
          fi

      - name: Explain + post to Discord (@everyone)
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO: ${{ steps.info.outputs.REPO }}
          SHA: ${{ steps.info.outputs.SHA }}
          TITLE: ${{ steps.info.outputs.TITLE }}
          BODY: ${{ steps.info.outputs.BODY }}
          ACTOR: ${{ steps.info.outputs.ACTOR }}
        shell: bash
        run: |
          python - <<'PY'
import os, json, requests, textwrap

repo   = os.environ["REPO"]
sha    = os.environ["SHA"]
title  = (os.environ.get("TITLE") or "").strip()
body   = (os.environ.get("BODY") or "").strip()
actor  = (os.environ.get("ACTOR") or "").strip()
channel_id = os.environ["DISCORD_CHANNEL_ID"]
bot_token  = os.environ["DISCORD_BOT_TOKEN"]
openai_key = os.environ.get("OPENAI_API_KEY")

def read(path):
    try:
        with open(path,"r",encoding="utf-8",errors="ignore") as f:
            return f.read()
    except FileNotFoundError:
        return ""

changed = [ln.strip() for ln in read("changed_files.txt").splitlines() if ln.strip()]
files_preview = ", ".join(changed[:6]) + (" …" if len(changed) > 6 else "") if changed else "(no files listed)"
diff_trimmed = read("diff.txt")[:6000]

def fallback():
    out = [f"• Summary: {title or '(no title)'}"]
    if body:
        out.append("• Notes: " + body.splitlines()[0])
    out.append(f"• Files: {files_preview}")
    out.append("• Follow-ups: run tests/checks for affected areas.")
    return "\n".join(out)

def explain(prompt: str) -> str:
    url = "https://api.openai.com/v1/responses"
    headers = {"Authorization": f
