name: Commit Summary to Discord

on:
  push:
    branches:
      - main
      - master

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate commit summary with OpenAI
        uses: KanHarI/gpt-commit-summarizer@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Send summary to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          SUMMARY=$(cat ./commit_summary.txt)
          echo "Sending summary to Discord..."
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"**New Commit Summary:**\n$SUMMARY\"}" \
               $DISCORD_WEBHOOK_URL
