name: Commits → Discord

on:
  push:
    branches: [ main ]   # change if your default branch is different

jobs:
  post-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Post every commit in this push as a line-item in one Discord message
      - name: Send commit(s) to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
          PARENT_SHA: ${{ github.event.before }}
          HEAD_SHA: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${WEBHOOK:-}" ]; then
            echo "Missing DISCORD_WEBHOOK_URL secret"; exit 1
          fi

          # Build a compact list of commits in this push
          BODY="**[Push]** \`${REPO}\` by ${ACTOR}\nCompare: https://github.com/${REPO}/compare/${PARENT_SHA}...${HEAD_SHA}\n"
          echo "$COMMITS_JSON" | jq -r '.[] | "\(.id[0:7]) · \(.author.username // .author.name) · \(.message | gsub("\n"; " ")) · https://github.com/'"$REPO"'/commit/\(.id)"' | \
          while IFS= read -r line; do
            BODY="$BODY\n$line"
          done

          # Also include a short file list for the head commit (handy context)
          FILES=$(git show --name-only --pretty="" "$HEAD_SHA" | head -n 8 | paste -sd ', ' -)
          [ -z "$FILES" ] && FILES="(no file list)"
          BODY="$BODY\n\n**Files (latest commit):** $FILES"

          # Keep under Discord 2000 chars
          BODY=$(printf '%s' "$BODY" | head -c 1900)

          jq -nc --arg content "$BODY" '{content:$content}' > payload.json
          curl -sS -H "Content-Type: application/json" -d @payload.json "$WEBHOOK"
