name: Commits → Discord (classic format)

on:
  push:
    branches: [ main ]   # change if your default branch is different

jobs:
  post-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send each commit to Discord (message, files, link)
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${WEBHOOK:-}" ]; then
            echo "Missing DISCORD_WEBHOOK_URL secret"; exit 1
          fi

          # If GitHub sent no commits (edge case), just exit
          COUNT=$(echo "$COMMITS_JSON" | jq 'length')
          if [ "$COUNT" -eq 0 ]; then
            echo "No commits in this push."
            exit 0
          fi

          # Loop through each commit in the push and post separately
          echo "$COMMITS_JSON" | jq -r '.[].id' | while read -r SHA; do
            # commit message for this SHA
            MSG=$(echo "$COMMITS_JSON" | jq -r --arg sha "$SHA" '.[] | select(.id==$sha) | .message')
            SAFE_MSG=$(printf "%s" "$MSG" | tr -d '\r' | sed 's/"/\\"/g' | head -c 900)

            # short file list for this specific commit
            FILES=$(git show --name-only --pretty="" "$SHA" | sed 's/"/\\"/g' | head -n 6 | paste -sd ', ' -)
            [ -z "$FILES" ] && FILES="(no file list)"

            COMMIT_URL="https://github.com/${REPO}/commit/${SHA}"
            BODY="**[Commit]** \`${REPO}\` @ \`${SHA:0:7}\` by ${ACTOR}
${COMMIT_URL}

**Message:** ${SAFE_MSG}
**Files:** ${FILES}"

            # keep under Discord's 2000-char limit
            BODY=$(printf '%s' "$BODY" | head -c 1900)

            jq -nc --arg content "$BODY" '{content:$content}' > payload.json
            curl -sS -H "Content-Type: application/json" -d @payload.json "$WEBHOOK"
          done
