name: Discord Commit Notifier

on:
  push:
    branches: [ main ]  # change if your default branch is different

jobs:
  post-to-discord:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send commit to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
          MSG: ${{ github.event.head_commit.message }}
        shell: bash
        run: |
          set -e
          COMMIT_URL="https://github.com/${REPO}/commit/${SHA}"
          FILES=$(git show --name-only --pretty="" "$SHA" | sed 's/"/\\"/g' | head -n 6 | paste -sd ', ' -)
          [ -z "$FILES" ] && FILES="(no file list)"
          SAFE_MSG=$(printf "%s" "$MSG" | sed 's/"/\\"/g')

          printf '%s' "{
            \"content\": \"**[Commit]** \`${REPO}\` @ \`${SHA:0:7}\` by ${ACTOR}\n${COMMIT_URL}\n\n**Message:** ${SAFE_MSG}\n**Files:** ${FILES}\"
          }" > payload.json

          curl -sS -X POST -H "Content-Type: application/json" \
            -d @payload.json "$WEBHOOK"

      - name: Explain commit in plain English
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # optional; script falls back if missing
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python scripts/explain_commit.py
